spring:
  #配置邮箱
  mail:
    host: smtp.qq.com #邮箱服务商的protocol服务器主机 #smtp.qq.com
    port: 465
    protocol: smtp #smtp
    username: xxx@qq.com #*****@qq.com
    nickname: iPhone12库存监控通知 #邮件通知主题
    password: xxx #邮箱账号密码或者三方登录授权码 #jwgteykojlf*****
    default-encoding:  UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: false #调试模式
    test-connection: false #启动项目时验证是否可以正确通信 默认为false



apple:
  #apple 库存地址
  stockAddress: https://reserve-prime.apple.com/CN/zh_CN/reserve/A/availability.json
  #apple 直营店信息
  stores: https://reserve-prime.apple.com/CN/zh_CN/reserve/A/stores.json