spring:
  thymeleaf:
    prefix: classpath:/templates/

  #配置邮箱
  mail:
    host: smtp.163.com #邮箱服务商的protocol服务器主机 #smtp.qq.com
    port: 465
    protocol: smtp #smtp
    username: liujiguijava@163.com  # #*****@qq.com
    nickname: 直营店库存监控小助手 #邮件通知主题
    password: VOBPMUWKNJAOZCNNI #邮箱账号密码或者三方登录授权码 #jwgteykojlf*****
    default-encoding:  UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: false #调试模式
    test-connection: true #启动项目时验证是否可以正确通信 默认为false


apple:
  #apple 库存地址
  stockAddress: https://reserve-prime.apple.com/CN/zh_CN/reserve/A/availability.json
  #apple 直营店信息
  stores: https://reserve-prime.apple.com/CN/zh_CN/reserve/A/stores.json


# 服务监控
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"